{% set name = "openmm-plumed" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmm/openmm-plumed/archive/v{{ version }}.tar.gz
  sha256: 906b6988f09ac3e28b2ce79e4682f483960c7c2caff19e4c9f99e35493606890
  # patches:
  #   - cmakelists.patch
  #   - fix-pip-install.patch

build:
  number: 0
  skip: true  # [win or (linux and cuda_compiler_version in (undefined, 'None', '10.2'))]
  missing_dso_whitelist:
    - "*/libcuda.*"    # [linux64 or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux and cuda_compiler_version != 'None']
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - cmake
    - make
    - conda-build
  host:
    - python
    - pip
    - openmm
    - plumed 2.7
    - swig <4.1
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx]
  run:
    - python
    - {{ pin_compatible('openmm', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('plumed', min_pin='x.x', max_pin='x.x') }}
    - ocl-icd  # [linux]
    - ocl-icd-system  # [linux]
    - khronos-opencl-icd-loader  # [osx]
    - ocl_icd_wrapper_apple      # [osx]

test:
  imports:
    - openmmplumed
  commands: |
    cd ${PREFIX}/share/openmm-plumed/tests
    set +e
    for f in Test*; do
      if [[ $f == *Cuda* || $f == *OpenCL* ]]; then
        continue
      fi
      ./${f}
      ((exitcode+=$?))
    done
    exit $exitcode


about:
  home: https://github.com/openmm/openmm-plumed
  license: MIT
  license_file: README.md
  summary: 'A connection between OpenMM and PLUMED'
  description: |
    This project provides a connection between OpenMM and PLUMED.
    It allows you to bias or analyze an OpenMM simulation based
    on collective variables.
  doc_url: https://github.com/openmm/openmm-plumed
  dev_url: https://github.com/openmm/openmm-plumed

extra:
  recipe-maintainers:
    - RaulPPelaez
    - raimis
    - jaimergp
    - peastman
